apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/instance: web-app
  name: web-app
  namespace: demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: web-app
    spec:
      containers:
      - image: quay.io/cytan/web-app:latest
        imagePullPolicy: Always
        name: web-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /deployments/config/application.yaml
          name: web-app-config
          subPath: application.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: web-app
        name: web-app-config